// Code generated by goctl. DO NOT EDIT.
// Source: code.proto

package server

import (
	"context"

	"github.com/giteexx/mygrpc/internal/logic"
	"github.com/giteexx/mygrpc/internal/svc"
	"github.com/giteexx/mygrpc/pb/api"
)

type GatewayServer struct {
	svcCtx *svc.ServiceContext
	api.UnimplementedGatewayServer
}

func NewGatewayServer(svcCtx *svc.ServiceContext) *GatewayServer {
	return &GatewayServer{
		svcCtx: svcCtx,
	}
}

func (s *GatewayServer) GetBalance(ctx context.Context, in *api.WayRequest) (*api.BalanceReply, error) {
	l := logic.NewGetBalanceLogic(ctx, s.svcCtx)
	return l.GetBalance(in)
}

func (s *GatewayServer) UsePhone(ctx context.Context, in *api.WayRequest) (*api.PhoneReply, error) {
	l := logic.NewUsePhoneLogic(ctx, s.svcCtx)
	return l.UsePhone(in)
}

func (s *GatewayServer) GetPhone(ctx context.Context, in *api.WayRequest) (*api.PhoneReply, error) {
	l := logic.NewGetPhoneLogic(ctx, s.svcCtx)
	return l.GetPhone(in)
}

func (s *GatewayServer) GetCode(ctx context.Context, in *api.WayRequest) (*api.CodeReply, error) {
	l := logic.NewGetCodeLogic(ctx, s.svcCtx)
	return l.GetCode(in)
}

func (s *GatewayServer) CodeFeed(ctx context.Context, in *api.WayRequest) (*api.EmptyReply, error) {
	l := logic.NewCodeFeedLogic(ctx, s.svcCtx)
	return l.CodeFeed(in)
}

func (s *GatewayServer) PhoneFeed(ctx context.Context, in *api.WayRequest) (*api.EmptyReply, error) {
	l := logic.NewPhoneFeedLogic(ctx, s.svcCtx)
	return l.PhoneFeed(in)
}

func (s *GatewayServer) Release(ctx context.Context, in *api.WayRequest) (*api.EmptyReply, error) {
	l := logic.NewReleaseLogic(ctx, s.svcCtx)
	return l.Release(in)
}
